import type { NextPage } from 'next';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import Header from '../components/Header';
import Main from './Main';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>glog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <Main/>
      </main>
      
    </div>
  )
}

export default Home
