version: 0.2

phases:
  pre_build:
    commands:
      - cd glog-client
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: client/build
